### ISSUE TITLE
Missing Method Declarations in src/main/java/util/CGUtils.java

### ISSUE THREAD

**Issue by ianorz** [ashkboos/LightWeightCGs#2]
I've encountered an issue while attempting to run code involving `src/main/java/util/CGUtils.java`. The specific problem arises with the `setSourceCallSitesToOptimizeMerge()` and `setGraph()` methods, which the compiler indicates cannot be resolved. Here is the snippet that leads to the error:

```java
final var pcg =
    new PartialJavaCallGraph(Constants.mvnForge, mavenCoordinate.getProduct(),
                             mavenCoordinate.getVersionConstraint(), -1,
                             Constants.opalGenerator,
                             partialCallGraph.classHierarchy,
                             partialCallGraph.graph);
if (partial) {
	pcg.setSourceCallSitesToOptimizeMerge();
	pcg.setGraph(new JavaGraph());
}
```

For this project, I've used [`[eu.fasten.analyzer.javacg-opal:0.0.18](https://github.com/fasten-project/fasten/packages/1276951?version=0.0.18)`](https://github.com/fasten-project/fasten/packages/1276951?version=0.0.18) instead of `en.fasten.analyzer:javacg-opal:0.0.14-snapshot`, so I investigated the possibility of a version-related issue. Despite thorough search efforts in the project's GitHub repository, I could not locate any declarations for these methods. This search included the entire GitHub repository, but there is still no result.

![image](https://github.com/ashkboos/LightWeightCGs/assets/64244156/f4e60548-88c9-40d9-804b-8af1c2a8d8ea)

So could someone provide guidance on this matter? Is there a version discrepancy I am overlooking, or are additional steps required to ensure compatibility?

Thank you for your assistance.

**Comment by mehdikeshani** [comment]
Are you using https://github.com/ashkboos/MyFasten and https://github.com/ashkboos/MyWala as dependencies?

**Comment by ianorz** [comment]
I see, these functions are in the packages you rewrote, and it will solve my problem, thanks

**Comment by ianorz** [comment]
Could you provide the jar packages for these two repositories, I had some problems when trying to package locally (such as test errors), I would be very grateful if you could provide them.

**Comment by mehdikeshani** [comment]
Please try -DskipTests. If you had problems I'll send you the jars

**Comment by ianorz** [comment]
The issue is solved and the code runs successfully, thank you very much for your help.
